### ISSUE TITLE
cant import tags from Tasks.org app 

### ISSUE THREAD

**Issue by Pleasantless** [etesync/android#159]
Tags created on website are buggy. sometimes they are imported to web, sometimes they just become an empty tag (no characters).
also tags created via Android app [Tasks.org](https://play.google.com/store/apps/details?id=org.tasks&hl=en&gl=US) are not imported to EteSync web. the following works:
_ tags/tasks created on web to app (sometimes)
_ tasks edited on web to app

**Comment by tasn** [comment]
I moved this to the Android app's repo, as it seems to just be a problem with the Android app/tasks.org/interaction between the two.

**Comment by devurandom** [comment]
I also noticed that tasks created using Tasks.org with EteSync being an external tasks provider (i.e. not using the EteSync client integrated into Tasks.org) loose their tags as soon as I trigger synchronisation (go to top of list and pull down). In the EteSync app I can see the "categories" being set when showing the "raw" form of the task. Just in Tasks.org they do not appear, even after synchronising again.

I fear that this might be bigger than just tags: A similar behaviour is affecting subtasks. See #161.

**Comment by tasn** [comment]
@devurandom, does it work for you with 2.2.0 or also doesn't work? I'm trying to take another look now, but will probably only have time on Wednesday...

**Comment by tasn** [comment]
Just tested it here again, and it works as expected. Latest EteSync app and latest Tasks.org (from f-droid).
1. I added a tag to an existing task on tasks.org
2. Waited until the data synced
3. Opened the web client and indeed the task has the tasks I set

I also:
1. Created a new task on tasks.org with tags set
2. Waited until the data synced
3. Opened the web client and indeed the task has the tasks I set.

I just can't reproduce what you are referring to. I can also see the tags correctly set as CATEGORIES in the raw data, so it's definitely working. Am I missing anything?

**Comment by devurandom** [comment]
> @devurandom, does it work for you with 2.2.0 or also doesn't work? I'm trying to take another look now, but will probably only have time on Wednesday...

I am using EteSync 2.1.5 and Tasks.org 10.4.1, the latest versions available on F-Droid. I will try again with EteSync 2.2.0 once it becomes available there.

I did not test with the web client. I see the tag vanishing within Tasks.org. I can confirm (s.a.) it is still present in the EteSync "raw" view.

**Comment by tasn** [comment]
I think that's the issue. It was fixed with 2.2.0. There was an issue with one of our deps that I believe is related.

**Comment by devurandom** [comment]
I am at EteSync 2.2.1 (and still Tasks.org 10.4.1) and the problem persists. Tasks.org "looses" the tag as soon as I synchronise the list, but in EteSync's raw view I can still see `CATEGORIES:Shopping`.

**Comment by tasn** [comment]
I'm pretty sure it's fixed now thanks to help from @abaker! Going to wait to hear from him to verify my fix fixed it and then will release a new version.

**Comment by devurandom** [comment]
@abaker said in tasks/tasks#1247 that this is fixed.

**Comment by tasn** [comment]
Yeah, it is. In 2.2.3.

**Comment by devurandom** [comment]
> Yeah, it is. In 2.2.3.

Hm, I do not get that version offered by F-Droid. (Version 2.2.2 is not available either.) I will check with them what's going on. Thanks for your support!

**Comment by tasn** [comment]
Pleasure

**Comment by devurandom** [comment]
The EteSync 2.2.3 update just arrived on F-Droid. After installing it, I synchronised EteSync, then I synchronised Tasks.org (using version 11.0), then I added tags to the tasks that previously had lost them and synchronised Tasks.org. The tags were removed again. This is not fixed, yet.

**Comment by devurandom** [comment]
> The EteSync 2.2.3 update just arrived on F-Droid. After installing it, I synchronised EteSync, then I synchronised Tasks.org (using version 11.0), then I added tags to the tasks that previously had lost them and synchronised Tasks.org. The tags were removed again. This is not fixed, yet.

@abaker suggested in https://github.com/tasks/tasks/issues/1252#issuecomment-749741295 that this might not be fixed before Tasks.org 11.0.1. That just arrived on F-Droid. I can happily confirm: It fixes the problem.

**Comment by tasn** [comment]
Great news, and sorry again for the trouble! It was a tough one that as you saw spread across the two apps.
