### ISSUE TITLE
Tasks and Events Disappear

### ISSUE THREAD

**Issue by michaelvandeweerd** [etesync/android#97]
Lately I've been having some problems with synchronizing my tasks. Somehow, the tasks seem to be disappearing locally. I've found that they reappear after making some change to them on another platform (usually Thunderbird) and synchronizing from the app. I've not yet found out what actually triggers this problem, but I've turned on logging in the hope that I can capture it when it happens again. My initial thought was that it happened when I created a new tasks through the app, but so far this does not seem to be the case.

This problem might also be present in the calendar sync, as there have been a few instances in which calendar events disappeared, which I solved by re-adding my account in the app.

You'll find a log file [here](https://github.com/etesync/android/files/3785495/etesync0.txt), in which I've captured syncing *after* making a small change to tasks that had disappeared, causing them to be added as new tasks by the app.

If I can manage to capture a log of the tasks disappearing I'll be sure to post them here. I hope you can figure something out!

**Comment by michaelvandeweerd** [comment]
A small update. Last night both my calendar events and tasks have completely disappeared. I've collected the logs:

- [22:37 - 22:54](https://github.com/etesync/android/files/3787161/etesync3.txt), this is where my calendar events seem to have disappeared. There are two exception that occur quite often, both of which suddenly stop appearing around line 126368, after an `Adding local calendar list Journal` message has been logged. This message has only been logs twice before this, so it might be related to the problem.
- [23:49](https://github.com/etesync/android/files/3787204/etesync4.txt)
- [02:44 - 03:04](https://github.com/etesync/android/files/3787215/etesync5.txt)
- [05:42](https://github.com/etesync/android/files/3787216/etesync6.txt)
- [06:40 - 06:53](https://github.com/etesync/android/files/3787217/etesync7.txt)

I hope this helps with identifying the cause of this problem!

**Comment by tasn** [comment]
Thanks for the report. You're not the first one to report it in the last couple of weeks. It seems to be a recent regression. I wonder what's up. Do all of the tasks of a certain collection disappear, or just a random one here and there?

Do you know in which version of EteSync it started happening? If it's happening consistently for you, are you able to downgrade the EteSync app to see if an older version works fine? Thanks!

I'll take a look at your logs in a moment, very useful to have them!

**Comment by tasn** [comment]
It seems it was introduced in version 1.9.0, could you please try with version 1.8.5 and see if you can get it to happen there?

Thanks!

**Comment by michaelvandeweerd** [comment]
All tasks and events disappear. However, after they have all disappeared, new tasks and events will appear as they're supposed to until they are all gone as well. 

I'm not sure at which version this started to happen, but I have downgraded to 1.8.5 like you said. I'll let you know whether the problem still occurs.

**Comment by tasn** [comment]
Thanks, let me know!

I'm pretty sure it's either 26ea8900a200d3b4c3accc730c03928b966af63d or for some reason  9ed172e23c57aaa3ee7d2d2f43c1e7c85a2c8c7b. Neither makes sense, but they are the two major changes that happened in this release.

**Comment by 3point2** [comment]
I've installed version 1.9.2 from https://stosb.com/~tom/app-release.apk and will update in a week if resolves the issue.

**Comment by tasn** [comment]
Thanks @3point2.
For reference: he reached out via email and said that 1.8.5 worked for him (which is where this idea came from). The version above is master +  a revert of  9ed172e. Let's see if this indeed fixes it. If not, I'll try also reverting 26ea890.

**Comment by tasn** [comment]
Any indication either way that things are working/not?

**Comment by michaelvandeweerd** [comment]
I haven't had any issues since downgrading to 1.8.5, so I suppose you're right about the problem being caused by one of the changes you've mentioned.

**Comment by tasn** [comment]
It's not me, it's @3point2 :)
Was it breaking immediately for you? As in, does this mean it's probably working? Or did it take a while each time to break?
Could you please try upgrading to the apk he linked to above and see if that makes it break? I'd like to release a new version with this reverted ASAP to make sure others aren't affected...

Thanks!

**Comment by betsythefc** [comment]
I am running into this problem and have been emailing with @tasn. Just installed the version from the website, and it is constantly erroring out and refreshing, with nothing syncing. Debug logs never generate for me to send.

**Comment by tasn** [comment]
Try uninstalling and reinstalling it? What kind of errors? That's very weird...

**Comment by betsythefc** [comment]
It says there are database errors in the notification tray, but that's all I get. Debug screen freezes, app needs to be force closed. I tried reinstalling -- same thing. I've downgraded to 1.8.5 for now, since I need my calendar :)

**Comment by tasn** [comment]
That's just odd... OK, thanks for reporting, I'll keep an eye out for this... I wonder why you're seeing it and no-one else. What ROM/device are you on? Got any more info on the error?
If you have access to ADB logcat may contain more information. Thanks!

**Comment by betsythefc** [comment]
I'm on a Moto G6, stock ROM, not rooted.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tasn** [comment]
Even weirder. Thanks for the info. I'll keep an eye out for similar reports.

**Comment by tasn** [comment]
Update: I just released 1.9.3 which includes the fix in the above APK (essentially the same, just with an updated version identifier). I think it fixes the issue, but even if it doesn't it's a good change to have. So I figured it's better to have a likely fix out for users sooner rather than later, even if it's not 100% confirmed yet.

**Comment by 3point2** [comment]
> Any indication either way that things are working/not?

I would usually experience the issue every 2-3 days and it's been 2 days with no issues so far with 1.9.2 for me.

**Comment by tasn** [comment]
@3point2, I assume you mean the APK from above (which is not really 1.9.2, it just used the same version string as the latest release). Anyhow, great, I released 1.9.3 which has the same fix as the APK you tried. I think this is now solved, though I'll wait a few days before closing this ticket.

Everyone: please report in a few days whether things work or are broken (or before if things break).

Thanks everyone, and sorry for the trouble. :|

**Comment by betsythefc** [comment]
I've installed the latest version (1.9.3) from F-Droid, and this morning the problem came back, I'm missing tasks in multiple lists.

**Comment by tasn** [comment]
Thanks for reporting back. Is this the case for other people too?

I wonder if it's an unrelated issue or the same thing. I have another commit I can revert if it's indeed the issue (and then we will be back to 1.8.5 which worked correctly), though I'd rather not revert that one unless I really need to.
@betsythefc: could you please reinstall etesync (version 1.9.3) so it brings back all the tasks and report back if anything disappears again? Sorry for the hassle. I'd just really like to find the issue rather than blindly disable other important fixes. :(

**Comment by betsythefc** [comment]
@tasn, I just edited my comment, saying I did just that :)

**Comment by tasn** [comment]
Ah OK. I reverted that one too and releasing 1.9.4 which should really fix it (essentially back to 1.8.5 in that regard). I'm annoyed but the more we wait more users will be affected.

**Comment by rogerm4242** [comment]
Just to follow up, I have had 1.9.3 installed from Google Play for 6 days now and have not seen my tasks disappear. Perhaps I was just fortunate enough not to trigger the issue.

**Comment by tasn** [comment]
@rogerm4242, thanks for the update! If you can avoid the 1.9.4 update for a few more days to see if 1.9.3 indeed fixed it for you, that would be great.
@betsythefc: if you could too try sticking with 1.9.3 (after doing the account remove/add workaround), that would be great too. I wonder if you'll get it back.

Either way 1.9.4 is like 1.8.5 now so should surely be fixed for most people.

**Comment by betsythefc** [comment]
I'll stay on 1.9.3

Thanks,
Bryce McNab

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tasn** [comment]
@betsythefc: thanks! Please let us know if the issue comes back.

**Comment by tasn** [comment]
Hey,

So is 1.9.3 good? @rogerm4242 and @betsythefc? Because 1.9.4 reverted a fix and I'd like to bring it back assuming it wasn't causing any issues.

**Comment by rogerm4242** [comment]
None of my tasks have disappeared while using 1.9.3. I would say it is good.

**Comment by tasn** [comment]
Thanks, please continue using 1.9.3 until 1.9.5 is out. I reverted this locally and will release 1.9.5 in a few days assuming I don't hear about any issues from anyone.

**Comment by tasn** [comment]
Anyhow, this is confirmed as fixed, so I'm closing the ticket. Thanks for everyone who helped testing!

Please, those of you who haven't upgraded to 1.9.4 yet, wait with the upgrade and report back if you experience any issues with 1.9.3. I'll wait a few more days (Friday) and then release 1.9.5.

**Comment by tasn** [comment]
I'm releasing 1.9.5.

Thanks everyone for testing!
